name: CI Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - run: npm install
      
      - name: npm build
        run: npm run-script build
      
      - run: npm test
